defaults:
  - data: default           # Kế thừa từ configs/data/config.yaml
  - model: default    # Kế thừa từ configs/model/config.yaml
  - training: default # Kế thừa từ configs/training/config.yaml
  - _self_

paths:
  data_dir: ${hydra.runtime.cwd}/data
  models_dir: ${hydra.runtime.cwd}/models
  outputs_dir: ${hydra.runtime.cwd}/outputs
  visualization_dir: ${hydra.runtime.cwd}/visualization
  logs_dir: ${hydra.runtime.cwd}/logs

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: default

default_model: random_forest

## Setup logs
hydra:
  run:
    dir: ${paths.logs_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.logs_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: "hydra_logging"
  verbose: false

log:
  root:
    handlers: ["file", "console"]
    level: INFO
  handlers:
    file:
      class: logging.FileHandler
      filename: ${hydra.job.name}.log
      formatter: simple
      directory: ${paths.logs_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    console:
      class: logging.StreamHandler
      formatter: simple
  formatters:
    simple:
      format: "[%(asctime)s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"