# .github/workflows/ci-cd.yml
name: ML Pipeline CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/
        
    - name: Run linting
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        mypy src/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t mlops-app:${{ github.sha }} .
      
    - name: Run Docker container tests
      run: |
        docker run mlops-app:${{ github.sha }} python -m pytest tests/

    # Add steps to push to registry if needed
    # - name: Push to registry
    #   run: |
    #     docker tag mlops-app:${{ github.sha }} registry/mlops-app:${{ github.sha }}
    #     docker push registry/mlops-app:${{ github.sha }}